Fix for error: has no attribute 'get_labels'
When running cells in order below AttributeError occurs as train_set.labels is created instead of train_set.get_labels.



---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-9-71ba0b13fd5d> in <module>()
      9 
     10 train_sampler = TaskSampler(
---> 11     train_set, n_way=N_WAY, n_shot=N_SHOT, n_query=N_QUERY, n_tasks=N_TRAINING_EPISODES
     12 )
     13 train_loader = DataLoader(

/usr/local/lib/python3.7/dist-packages/easyfsl/samplers/task_sampler.py in __init__(self, dataset, n_way, n_shot, n_query, n_tasks)
     39 
     40         self.items_per_label = {}
---> 41         for item, label in enumerate(dataset.get_labels()):
     42             if label in self.items_per_label.keys():
     43                 self.items_per_label[label].append(item)

AttributeError: 'Omniglot' object has no attribute 'get_labels'